services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telegraph
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: iGKUJGl3JbTCvko8dI9zw6qYfwWRiH98X5GUnUQFKVW
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: telegraph
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: