spring.application.name=telegraph

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/telegraph}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

jwt.secret=${JWT_SECRET}

cors.allowed-origins=${CORS_ORIGINS:http://localhost:63342}

