spring.application.name=telegraph

spring.datasource.url=jdbc:postgresql://localhost:5432/telegraph
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

#jwt.secret=${JWT_SECRET}
jwt.secret=iGKUJGl3JbTCvko8dI9zw6qYfwWRiH98X5GUnUQFKVW